In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
basicArray = np.array ([1, 2, 3], dtype = 'int32')

In [4]:
basicArray

array([1, 2, 3])

In [5]:
anotherArray = np.array ([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

In [6]:
anotherArray

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
anotherArray.ndim

2

In [8]:
anotherArray.shape

(2, 3)

In [9]:
anotherArray.dtype

dtype('float64')

In [10]:
anotherArray.itemsize

8

In [12]:
anotherArray.nbytes

48

In [13]:
anotherArray.size

6

### Extraction of element

In [14]:
anotherArray

array([[9., 8., 7.],
       [6., 5., 4.]])

In [15]:
anotherArray[1, 1]

5.0

In [16]:
anotherArray[0, :]

array([9., 8., 7.])

In [17]:
anotherArray[:, 1]

array([8., 5.])

In [19]:
### [row, startindex : endindex : steps]
anotherArray[0, 1:-1:2]

array([8.])

In [20]:
anotherArray

array([[9., 8., 7.],
       [6., 5., 4.]])

In [21]:
anotherArray[1, 1] = 20

In [22]:
anotherArray

array([[ 9.,  8.,  7.],
       [ 6., 20.,  4.]])

In [26]:
three = np.array ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [27]:
three.shape

(2, 2, 2)

In [28]:
three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
three[0, 1, 1]

4

In [30]:
three[:, 1, :] = [[9, 8], [8, 8]]

In [31]:
three

array([[[1, 2],
        [9, 8]],

       [[5, 6],
        [8, 8]]])

### Data Science oriented methods

In [32]:
np.zeros ((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones ((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
np.full ((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
anotherArray

array([[ 9.,  8.,  7.],
       [ 6., 20.,  4.]])

In [36]:
np.full_like (anotherArray, 4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [39]:
np.random.rand (4, 2)

array([[0.13044173, 0.43315076],
       [0.68552165, 0.95968997],
       [0.83480258, 0.19054515],
       [0.2211441 , 0.37999552]])

In [43]:
np.random.randint (-4, 8, size = (3, 3))

array([[-4, -4,  0],
       [-2,  6, -2],
       [ 2, -1, -1]])

In [44]:
np.identity (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Math Operations

In [45]:
randomArray = np.array ([1, 2, 3, 4])

In [46]:
randomArray

array([1, 2, 3, 4])

In [47]:
randomArray + 2

array([3, 4, 5, 6])

In [48]:
randomArray - 2

array([-1,  0,  1,  2])

In [49]:
randomArray * 2

array([2, 4, 6, 8])

In [50]:
np.cos (randomArray)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra